### ISSUE TITLE
The one shot result against the expected result

### ISSUE THREAD

**Issue by woshiodoman** [CSer-Tang-hao/FS-KTN#2]
After I have executed the code '$ python Test_Vis_Kno.py --network Conv64 --test_nExemplars 1',I just got the AccuracyNovel is 53.97 +- 0.72 %,but the result claimed in your instructions is 63.83 +- 0.77%.

**Comment by CSer-Tang-hao** [comment]
> After I have executed the code '$ python Test_Vis_Kno.py --network Conv64 --test_nExemplars 1',I just got the AccuracyNovel is 53.97 +- 0.72 %,but the result claimed in your instructions is 63.83 +- 0.77%.

Sorry for the late reply. Please follow the steps in ReadMe carefully. If you have any question, you can email me, thanks!
